// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewCityInfo.API.DbContexts;

#nullable disable

namespace NewCityInfo.API.Migrations
{
    [DbContext(typeof(CityInfoContext))]
    [Migration("20231127092045_DataSeed")]
    partial class DataSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("NewCityInfo.API.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "city description 1",
                            Name = "city1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "city description 2",
                            Name = "city2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "city description 3",
                            Name = "city3"
                        });
                });

            modelBuilder.Entity("NewCityInfo.API.Entities.PointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("PointOfInterests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Description = "point of interest description 1",
                            Name = "pointOfInterest1"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Description = "point of interest description 2",
                            Name = "pointOfInterest2"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            Description = "point of interest description 3",
                            Name = "pointOfInterest3"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            Description = "point of interest description 4",
                            Name = "pointOfInterest4"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 3,
                            Description = "point of interest description 5",
                            Name = "pointOfInterest5"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 3,
                            Description = "point of interest description 6",
                            Name = "pointOfInterest6"
                        });
                });

            modelBuilder.Entity("NewCityInfo.API.Entities.PointOfInterest", b =>
                {
                    b.HasOne("NewCityInfo.API.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });
#pragma warning restore 612, 618
        }
    }
}
